### PR TITLE
[SAP] Added set_size() to rw_handles

### PR DESCRIPTION
**Pull request by hemna**
This patch is needed to properly set the internal private attribute of _vmdk_size to the VmdkHandle base class.

When cinder gets a vmdk handle during restore, it needs to specify the actual total size bytes of the vmdk data that has been backed up in order to know when the handle has correctly written all of the data to the vmdk file.  From cinder's backup service the VmdkWriteHandle is wrapped in a eventlet thread Proxy object, which only allows calling methods to set data behind the
Proxy.   Previously Cinder was trying to directly set the
private attribute self._vmdk_size, which was never making it into
the actual VMdkWriteHandle instance itself.

The eventlet Proxy object only allows setting data via wrapping the original object's methods.  Hence the need for creating the set_size() method.

https://eventlet.net/doc/threading.html?highlight=proxThe%20eventlet%20Proxy#eventlet.tpool.Proxy

### CODE REVIEW

**Comment by hemna** [comment]
This should be testing against python 3.8 for wallaby not python 2.7

**Review by grandchild — CHANGES_REQUESTED** [review]
The code itself looks fine.

The CI is having some issues.

The last line in the commit message, the link, includes a highlight to `prox` (which is probably not needed) + something that looks like the start of the previous paragraph.

**Comment by grandchild** [comment]
https://github.wdf.sap.corp/cc/secrets/pull/10833

**Comment by grandchild** [comment]
@hemna Could you amend the commit (you don't have to change anything, just `--amend`) to re-trigger the pipeline? It's in a confused state right now.

**Review by grandchild — APPROVED** [review]

**Pull request merged**
